### ISSUE TITLE
WebApi hello world snippet is missing

### ISSUE THREAD

**Issue by gomnet** [J0rgeSerran0/vscode-csharp-snippets#1]
Hi Jorge,

It would be appreciate to have an snippet for creating new webapi project (core type).

I hope it helps to you for having more useful extension in @code.

Thanks so much in advance.

Best regards,
David.

**Comment by J0rgeSerran0** [comment]
Your suggestion is welcome!

I have that snippet (and more) on my roadmap. :)

Thank you very much @gomnet 

Stay tuned!
