### ISSUE TITLE
High memory consumption 

### ISSUE THREAD

**Issue by Novack** [J0rgeSerran0/vscode-csharp-snippets#12]
Im experiencing high mem consumption with extension version v1.1.0 and latest vscodium version (1.81.1). 

My environment is for the Unity stack, so core extensions are: C#, C# Dev Kit, Intellicode for C#, Unity and Plastic extension may be relevant too.

**Comment by Novack** [comment]
This was incorrect. Im tracking the described memory peak issue and at one point it magically improved by disabling this extension, but after further testing the consumption peak appeared again even with the extension disabled again. 
Apologies.

**Comment by J0rgeSerran0** [comment]
Don't worry @Novack 
It was the first time that I was receiving a problem issue related with a high mem consumption with the extension

Kr,
Jorge
